### ISSUE TITLE
Send audios bigger than 10Mo => "artist - title" and duration not correct

### ISSUE THREAD

**Issue by abumalick** [atipugin/telegram-bot-ruby#98] opened 2017-01-14 21:10 UTC
Hello,
Thank you VERY MUCH for your API, it is really great to code bot with ruby with it.

I am experiencing a bug (maybe due to Faraday), I don't know how to debug that.

I have an app that send mp3 files as send message, here is the code : 

`bot.api.send_audio(chat_id: message.chat.id, audio: Faraday::UploadIO.new(filename, 'audio/mp3'))`

Everything works well for files under 10Mo, but if I try with files bigger than 10Mb, it send it but I don't get ID3 tags displayed in telegram 

* name of the file is displayed instead of "artist - title"
* total time of the audio is not displayed (0:00)

When I download the file from telegram and I check, id3 tags are ok, and md5sum of the file is same as original.

I tried with these files: 

* 11Mb: `http://download.quran.islamway.net/quran3/31/8091/32/020.mp3` don't work
* 9.9Mb: `http://download.quran.islamway.net/quran3/31/8091/32/021.mp3` works
* 26.5Mb: `http://server9.mp3quran.net/hthfi/007.mp3` don't works
* 9.7Mb: `http://server9.mp3quran.net/hthfi/008.mp3` works

I tried the app on my ubuntu computer and on heroku I get same result.

If I upload the file manually (020.mp3) from telegram desktop, it works,

Can you help me find the problem ?
Thanks

**Comment by abumalick** [comment] 2017-01-15 06:24
A quick fix to that : 

`bot.api.send_audio(chat_id: message.chat.id, audio: Faraday::UploadIO.new(filename, 'audio/mp3'), performer: id3.artist, title: id3.title)`

**Comment by ivanovaleksey** [comment] 2017-04-17 11:51
@abumalick looks like it is Telegram API related.
The problem is solved? Can you close the issue?

**Comment by abumalick** [comment] 2017-04-17 12:57
I used the workaround,
you can close it it is not related to your code

**Comment by ivanovaleksey** [comment] 2017-04-17 13:24
Please close it yourself, I don't have the ability.

**Closed** 2017-04-17 13:25 UTC
