### ISSUE TITLE
How do I stop my bot without repeating the last message, next time I start it up?

### ISSUE THREAD

**Issue by protektwar** [atipugin/telegram-bot-ruby#233] opened 2021-04-18 14:10 UTC
How can I stop this bot and flush/acknowledge the last message received, without having it repeated next time when I start the bot?
For instance it receive a "/quit" command and it run an `exit(true)` in my code. Next time when I start my bot it will stop right away as the last message/command is repeating...

**Comment by ivanovaleksey** [comment] 2021-04-18 17:30
Hi @protektwar, sounds interesting. I didn't mention that messages get duplicated after stop/start or restart though I didn't do it intentionally.
I think it is all about `offset` option in `Client`. It is [getting updated](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/client.rb#L41) before yielding message to a block specified.
I guess you can try [to pass](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/client.rb#L12) initial `offset` on `Client` initialization. You could store `offset` somehow while handling `/quit` command before exiting application.

**Comment by protektwar** [comment] 2021-04-19 08:17
```
  def saveLastMsgID(id)
    File.open(@lastMsgID_filename, "wb") { |file|
      file.write(id)
    }
  end

  def loadLastMsgID
    File.open(@lastMsgID_filename){ |file|
    @lastMsgID = file.gets
    }
  end
```
and inside `bot.listen` block
```
 bot.listen do |message|
        if ( bot.options[:offset].to_s == @lastMsgID.to_s )
         break
       end
 end

```

**Comment by ivanovaleksey** [comment] 2021-04-19 08:26
It is not what I meant but it is up to you. If the problem is solved please close the issue.

**Closed** 2021-04-19 08:29 UTC
