### ISSUE TITLE
Issue in updated message logging

### ISSUE THREAD

**Issue by delneg** [atipugin/telegram-bot-ruby#57] opened 2016-05-22 14:06 UTC
Looks like it can't log updated messages.

Traceback:
/usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:61:in `log_incoming_message': undefined method `from' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:39:in `block in fetch_updates'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:35:in `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:35:in `fetch_updates'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:27:in `listen'
	from /root/Serialtimerbot/main_bot.rb:61:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:20:in `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:8:in `run'
	from /root/Serialtimerbot/main_bot.rb:55:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/controller.rb:56:in `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `call'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'

**Comment by mufid** [comment] 2016-05-22 14:45
Got that problem, too:

```
14:43:51 norm.1 | /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:61:in `log_incoming_message': undefined method `from' for nil:NilClass(NoMethodError)
14:43:51 norm.1 |       from /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:39:in `block in fetch_updates'
14:43:51 norm.1 |       from /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:35:in `each'
14:43:51 norm.1 |       from /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:35:in `fetch_updates'
14:43:51 norm.1 |       from /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:27:in `listen'
14:43:51 norm.1 |       from /home/frontend/repo/repost/lib/image_repost_bot.rb:56:in `block in run_standalone'
14:43:51 norm.1 |       from /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:20:in `run'
14:43:51 norm.1 |       from /home/frontend/.rvm/gems/ruby-2.3.1/gems/telegram-bot-ruby-0.5.1/lib/telegram/bot/client.rb:8:in `run'
14:43:51 norm.1 |       from /home/frontend/repo/repost/lib/image_repost_bot.rb:54:in `run_standalone'
14:43:51 norm.1 |       from bin/image_repost_standalone:16:in `<main>'
1
```

**Comment by delneg** [comment] 2016-05-22 14:46
I ended up commenting log_incoming_message code directly in the client.rb

**Comment by atipugin** [comment] 2016-05-22 15:18
According docs, sometimes `Message` can have empty `from` attribute (i.e. channel message). So, yes, it's an issue, going to fix it soon.

**Comment by atipugin** [comment] 2016-05-22 15:56
Yes, there is an issue for now, going to fix it with next release (in next few days).

**Comment by atipugin** [comment] 2016-05-22 16:09
Please update gem to `0.5.2` and try again.

**Comment by mufid** [comment] 2016-05-23 01:19
Seems like the problem is gone. Thanks for the fast response! I think we can close this now.

**Closed** 2016-05-23 06:18 UTC

**Comment by EVOKE-LEKTRIQUE** [comment] 2017-01-03 14:52
i got this error too !!
`/usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:59:in `log_incoming_message': undefined method `from' for nil:NilClass (NoMethodError)          
        from /usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:37:in `block in fetch_updates'                                                     
        from /usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:33:in `each'                                                                       
        from /usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:33:in `fetch_updates'                                                              
        from /usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:25:in `listen'                                                                     
        from konachan.rb:196:in `block in <main>'                                                                                                                         
        from /usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:18:in `run'                                                                        
        from /usr/local/bundle/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:8:in `run'                                                                         
        from konachan.rb:195:in `<main>'                                                               `
